// examples/with-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'lab-angular';
  styledButton: any = { 
    width: '200px',
    height: '80px',
    backgroundColor: '#ff57ac'
  }

  handleClick(e) {
    console.log(e.detail);
  }
}

<section>
  <h1 class="page-title">Angular</h1>
  <hr/>
  <span class="spacing">
    <legods-button (buttonClick)="handleClick($event)">Default</legods-button>
  </span>
  <span class="spacing">
    <legods-button variant="primary" (buttonClick)="handleClick($event)">Primary</legods-button>
  </span>
  <span class="spacing">
    <legods-button variant="secondary" (buttonClick)="handleClick($event)">Secondary</legods-button>
  </span>
  <span class="spacing">
    <legods-button variant="tertiary" (buttonClick)="handleClick($event)">Tertiary</legods-button>
  </span>
  <span class="spacing">
    <legods-button variant="dark" (buttonClick)="handleClick($event)">Dark</legods-button>
  </span>

  <h3 class="section-title">Flat Buttons</h3>
  <section>
    <span class="spacing">
      <legods-button flat (buttonClick)="handleClick($event)">Default</legods-button>
    </span>
    <span class="spacing">
      <legods-button flat (buttonClick)="handleClick($event)" variant="primary">Primary</legods-button>
    </span>
    <span class="spacing">
      <legods-button flat (buttonClick)="handleClick($event)" variant="secondary">Secondary</legods-button>
    </span>
    <span class="spacing">
      <legods-button flat (buttonClick)="handleClick($event)" variant="tertiary">Tertiary</legods-button>
    </span>
    <span class="spacing">
      <legods-button flat (buttonClick)="handleClick($event)" variant="dark">Dark</legods-button>
    </span>
  </section>

  <h3 class="section-title">Disabled Button</h3>
  <section>
    <span class="spacing">
      <legods-button (buttonClick)="handleClick($event)" flat variant="primary" disabled>disabled flat button</legods-button>
    </span>
    <span class="spacing">
      <legods-button (buttonClick)="handleClick($event)" variant="primary" disabled>disabled button</legods-button>
    </span>
  </section>

  <h3 class="section-title">Full Width Button</h3>
  <section>
    <span class="spacing">
      <legods-button (buttonClick)="handleClick($event)" flat full>Full width flat button</legods-button>
    </span>
    <span class="spacing">
      <legods-button (buttonClick)="handleClick($event)" full>Full with button</legods-button>
    </span>
  </section>

  <h3 class="section-title">Self Styled Button</h3>
  <section>
    <span class="spacing">
      <legods-button 
        [styles]="styledButton"
        aria-label="Button with customizable style (pink color) and a11y attributes"
        (buttonClick)="handleClick($event)">
        Styled Button
      </legods-button>
    </span>
  </section>
</section>

// examples/with-react/src/App.js
import React from 'react';
import styled from 'styled-components';
import { LegodsButton } from '@lego-ds/react';

const Spacing = styled.span`
  margin: 10px;
`;

function App() {
  const handleClick = (event) => {
    console.log(event)
  }

  return (
    <div className="App">
      <img src="./logo.png" width="80px" />
      <hr />
      <section>
        <Spacing>
          <LegodsButton onButtonClick={event => handleClick(event.detail)}>Default</LegodsButton>
        </Spacing>
        <Spacing>
          <LegodsButton variant="primary" onButtonClick={event => handleClick(event.detail)}>Primary</LegodsButton>
        </Spacing>
        <Spacing>
          <LegodsButton variant="secondary" onButtonClick={event => handleClick(event.detail)}>Secondary</LegodsButton>
        </Spacing>
        <Spacing>
          <LegodsButton variant="tertiary" onButtonClick={event => handleClick(event.detail)}>Tertiary</LegodsButton>
        </Spacing>
        <Spacing>
          <LegodsButton variant="dark" onButtonClick={event => handleClick(event.detail)}>Dark</LegodsButton>
        </Spacing>
      </section>

      <h3>Flat Buttons</h3>
      <section>
        <Spacing>
          <LegodsButton flat onButtonClick={event => handleClick(event.detail)}>Default</LegodsButton>
        </Spacing>
        <Spacing>
          <LegodsButton flat variant="primary" onButtonClick={event => handleClick(event.detail)}>Primary</LegodsButton>
        </Spacing>
        <Spacing>
          <LegodsButton flat variant="secondary" onButtonClick={event => handleClick(event.detail)}>Secondary</LegodsButton>
        </Spacing>
        <Spacing>
          <LegodsButton flat variant="tertiary" onButtonClick={event => handleClick(event.detail)}>Tertiary</LegodsButton>
        </Spacing>
        <Spacing>
          <LegodsButton flat variant="dark" onButtonClick={event => handleClick(event.detail)}>Dark</LegodsButton>
        </Spacing>
      </section>

      <h3>Disabled Button</h3>
      <section>
        <Spacing>
          <LegodsButton flat variant="primary" disabled onButtonClick={event => handleClick(event.detail)}>disabled flat button</LegodsButton>
        </Spacing>
        <Spacing>
          <LegodsButton variant="primary" disabled onButtonClick={event => handleClick(event.detail)}>disabled button</LegodsButton>
        </Spacing>
      </section>

      <h3>Full Width Button</h3>
      <section>
        <Spacing>
          <LegodsButton flat full onButtonClick={event => handleClick(event.detail)}>Full width flat button</LegodsButton>
        </Spacing>
        <Spacing>
          <LegodsButton full onButtonClick={event => handleClick(event.detail)}>Full with button</LegodsButton>
        </Spacing>
      </section>

      <h3>Styled Button</h3>
      <section>
        <Spacing>
          <LegodsButton
            variant='secondary'
            aria-label="teste de a11y"
            styles={{ 
              width: '200px',
              height: '80px',
              backgroundColor: '#ff57ac'
            }}
            onButtonClick={event => handleClick(event.detail)}>
              Styled Button
          </LegodsButton>
        </Spacing>
      </section>
    </div>
  );
}

export default App;
